name: Rust audit

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master 

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install rust auditing tools
      run: cargo install cargo-audit
    - name: Audit
      run: cargo audit
